
name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r23b
        link-to-sdk: true

    - name: 安装JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: 授予gradlew的执行权限
      run: chmod +x gradlew

    - name: 使用Gradle构建
      # run: ./gradlew build
      run: ./gradlew assembleRelease

    - name: 上传 GitHub Actions 构建的 APK
      uses: actions/upload-artifact@v4
      with:
        name: scene-dev
        path: ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk
